/**
 * Generates supabase/seed.sql from the static catalog in src/data, so the
 * database and the static fallback start from identical content.
 *
 *   npm run db:seed:generate
 *
 * The seed contains catalog content only: no users, orders, reviews,
 * ratings or coupons.
 */
import { CATEGORIES } from '../src/data/categories.ts';
import { COLLECTIONS } from '../src/data/collections.ts';
import { PRODUCTS, VEKTOR_LAB_CREATOR } from '../src/data/products.ts';

function text(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function json(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  return `${text(JSON.stringify(value))}::jsonb`;
}

function textArray(values: string[]): string {
  if (!values.length) return `'{}'::text[]`;
  return `array[${values.map(text).join(', ')}]::text[]`;
}

const lines: string[] = [];
lines.push('-- Generated by scripts/generate-seed.ts — do not edit by hand.');
lines.push('-- Catalog content only (no users, orders, reviews or coupons).');
lines.push('begin;');
lines.push('');

lines.push(
  `insert into public.creators (id, slug, name, is_internal, status) values (${text(VEKTOR_LAB_CREATOR.id)}, ${text(
    VEKTOR_LAB_CREATOR.slug,
  )}, ${text(VEKTOR_LAB_CREATOR.name)}, true, 'active') on conflict (id) do nothing;`,
);
lines.push('');

// Parents first so the foreign key is satisfied.
const orderedCategories = [...CATEGORIES].sort((a, b) => Number(Boolean(a.parentId)) - Number(Boolean(b.parentId)));
for (const c of orderedCategories) {
  lines.push(
    `insert into public.categories (id, slug, parent_id, name, description, tone, sort_order) values (${text(c.id)}, ${text(
      c.slug,
    )}, ${text(c.parentId)}, ${json(c.name)}, ${json(c.description)}, ${text(c.tone)}, ${c.sortOrder}) on conflict (id) do nothing;`,
  );
}
lines.push('');

for (const p of PRODUCTS) {
  const columns = [
    ['id', text(p.id)],
    ['slug', text(p.slug)],
    ['status', text(p.status)],
    ['product_type', text(p.productType)],
    ['title', json(p.title)],
    ['subtitle', json(p.subtitle)],
    ['short_description', json(p.shortDescription)],
    ['description', json(p.description)],
    ['category_id', text(p.categoryId)],
    ['secondary_category_ids', textArray(p.secondaryCategoryIds)],
    ['goals', textArray(p.goals)],
    ['tags', textArray(p.tags)],
    ['formats', textArray(p.formats)],
    ['software', textArray(p.software)],
    ['technologies', textArray(p.technologies)],
    ['audience', json(p.audience)],
    ['use_cases', json(p.useCases)],
    ['features', json(p.features)],
    ['included_items', json(p.includedItems)],
    ['requirements', json(p.requirements)],
    ['specs', json(p.specs)],
    ['faq', json(p.faq)],
    ['price_amount', String(p.price.amount)],
    ['currency', text(p.price.currency)],
    ['compare_at_amount', p.compareAtAmount === null ? 'null' : String(p.compareAtAmount)],
    ['license_tier', text(p.license)],
    ['delivery', text(p.delivery)],
    ['version', text(p.version)],
    ['last_updated', text(p.lastUpdated)],
    ['file_size_label', text(p.fileSize)],
    ['creator_id', text(p.creator.id)],
    ['is_featured', String(p.isFeatured)],
    ['sort_order', String(p.sortOrder)],
    ['published_at', text(p.publishedAt)],
  ] as const;
  lines.push(
    `insert into public.products (${columns.map(([c]) => c).join(', ')}) values (${columns
      .map(([, v]) => v)
      .join(', ')}) on conflict (id) do nothing;`,
  );
}
lines.push('');

for (const c of COLLECTIONS) {
  lines.push(
    `insert into public.collections (id, slug, title, description, featured_product_id, is_published, sort_order) values (${text(
      c.id,
    )}, ${text(c.slug)}, ${json(c.title)}, ${json(c.description)}, ${text(c.featuredProductId)}, true, ${c.sortOrder}) on conflict (id) do nothing;`,
  );
  c.productIds.forEach((productId, index) => {
    lines.push(
      `insert into public.collection_products (collection_id, product_id, sort_order) values (${text(c.id)}, ${text(
        productId,
      )}, ${index}) on conflict do nothing;`,
    );
  });
}
lines.push('');
lines.push('commit;');

process.stdout.write(`${lines.join('\n')}\n`);
