-- =====================================================================
-- Vektor Lab — core schema
--
-- Security model
--   * Row Level Security is enabled on every table.
--   * Public visitors can read published catalog content only.
--   * Customers can read their own profile, orders, entitlements and
--     downloads, manage their own cart/wishlist, and review products they own.
--   * Orders, payments, entitlements and downloads are written only by the
--     server using the service-role key, after explicit verification.
--   * Roles live in public.profiles and cannot be changed by the user.
--   * Paid files live in a private storage bucket; buyers receive short-lived
--     signed URLs generated by the server after an ownership check.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- Profiles & roles
-- ---------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null default '',
  full_name text check (full_name is null or char_length(full_name) <= 120),
  role text not null default 'buyer'
    check (role in ('buyer', 'creator', 'editor', 'admin', 'super_admin')),
  locale text not null default 'ru' check (locale in ('ru', 'en', 'uz')),
  marketing_opt_in boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('admin', 'super_admin'), false);
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('editor', 'admin', 'super_admin'), false);
$$;

-- Create a profile for every new auth user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, locale)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(left(new.raw_user_meta_data ->> 'full_name', 120), ''),
    case when new.raw_user_meta_data ->> 'locale' in ('ru', 'en', 'uz')
      then new.raw_user_meta_data ->> 'locale' else 'ru' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keep profile email in sync with the auth record.
create or replace function public.handle_user_email_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.email is distinct from old.email then
    update public.profiles set email = coalesce(new.email, '') where id = new.id;
  end if;
  return new;
end;
$$;

create trigger on_auth_user_email_changed
  after update of email on auth.users
  for each row execute function public.handle_user_email_change();

-- Roles can only be changed by the service role (server, after an explicit
-- super-admin check) or directly in SQL — never by the user themselves.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
as $$
begin
  if new.role is distinct from old.role
     and coalesce(auth.role(), '') <> 'service_role'
     and current_user not in ('postgres', 'supabase_admin') then
    raise exception 'Changing roles is not permitted' using errcode = '42501';
  end if;
  return new;
end;
$$;

create trigger profiles_protect_role before update on public.profiles
  for each row execute function public.protect_profile_role();

-- ---------------------------------------------------------------------
-- Creators (Vektor Lab today; third-party creators later)
-- ---------------------------------------------------------------------

create table public.creators (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null,
  bio jsonb not null default '{}'::jsonb,
  website text,
  user_id uuid references public.profiles (id) on delete set null,
  is_internal boolean not null default false,
  -- Revenue share for future third-party creators (basis points, 0–10000).
  revenue_share_bps integer check (revenue_share_bps is null or revenue_share_bps between 0 and 10000),
  status text not null default 'active' check (status in ('pending', 'active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger creators_updated_at before update on public.creators
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------
-- Catalog
-- ---------------------------------------------------------------------

create table public.categories (
  id text primary key check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  parent_id text references public.categories (id) on delete restrict,
  name jsonb not null,
  description jsonb not null default '{}'::jsonb,
  tone text not null default 'business'
    check (tone in ('design', 'development', 'ai', 'business', 'marketing', 'product', 'notion', 'data', 'slides', 'assets')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (parent_id is null or parent_id <> id)
);

create trigger categories_updated_at before update on public.categories
  for each row execute function public.set_updated_at();

create table public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  product_type text not null check (product_type in (
    'spreadsheet', 'notion-template', 'presentation', 'playbook', 'ui-kit', 'design-system', 'code',
    'prompt-pack', 'workflow', '3d', 'icons', 'illustrations', 'guide', 'bundle')),

  title jsonb not null,
  subtitle jsonb not null default '{}'::jsonb,
  short_description jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,

  category_id text not null references public.categories (id) on delete restrict,
  secondary_category_ids text[] not null default '{}',
  goals text[] not null default '{}',
  tags text[] not null default '{}',
  formats text[] not null default '{}',
  software text[] not null default '{}',
  technologies text[] not null default '{}',

  audience jsonb not null default '{"ru": [], "en": []}'::jsonb,
  use_cases jsonb not null default '{"ru": [], "en": []}'::jsonb,
  features jsonb not null default '{"ru": [], "en": []}'::jsonb,
  included_items jsonb not null default '{"ru": [], "en": []}'::jsonb,
  requirements jsonb not null default '{"ru": [], "en": []}'::jsonb,
  specs jsonb not null default '[]'::jsonb,
  faq jsonb not null default '[]'::jsonb,

  -- Money: numeric amount + ISO currency, never a formatted string.
  price_amount numeric(12, 2) not null check (price_amount >= 0),
  currency char(3) not null default 'RUB' check (currency ~ '^[A-Z]{3}$'),
  -- Only set when there is a genuine regular price to compare against.
  compare_at_amount numeric(12, 2) check (compare_at_amount is null or compare_at_amount > price_amount),

  license_tier text not null default 'commercial' check (license_tier in ('personal', 'commercial', 'team', 'extended')),
  delivery text not null default 'download' check (delivery in ('download', 'external-link', 'download-and-link')),
  version text not null default '1.0',
  last_updated date not null default current_date,
  file_size_label text,

  creator_id uuid not null references public.creators (id) on delete restrict,
  is_featured boolean not null default false,
  sort_order integer not null default 0,

  -- Maintained by triggers from approved reviews / successful downloads.
  rating_average numeric(3, 2),
  rating_count integer not null default 0,
  download_count integer not null default 0,

  thumbnail_path text,
  preview_url text check (preview_url is null or preview_url ~ '^https://'),
  documentation_url text check (documentation_url is null or documentation_url ~ '^https://'),
  seo_title jsonb,
  seo_description jsonb,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create index products_status_idx on public.products (status);
create index products_category_idx on public.products (category_id);

create trigger products_updated_at before update on public.products
  for each row execute function public.set_updated_at();

create or replace function public.set_published_at()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'published' and new.published_at is null then
    new.published_at = now();
  end if;
  return new;
end;
$$;

create trigger products_published_at before insert or update of status on public.products
  for each row execute function public.set_published_at();

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  storage_path text not null,
  alt jsonb not null default '{}'::jsonb,
  kind text not null default 'gallery' check (kind in ('thumbnail', 'gallery', 'og')),
  sort_order integer not null default 0,
  width integer,
  height integer,
  created_at timestamptz not null default now()
);

create index product_images_product_idx on public.product_images (product_id);

-- Deliverables. Paid files live in the private bucket; external links
-- (e.g. Notion duplicate links) are only visible to owners and staff.
create table public.product_files (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  kind text not null default 'download' check (kind in ('download', 'documentation', 'external_link')),
  label jsonb not null default '{}'::jsonb,
  storage_path text,
  external_url text check (external_url is null or external_url ~ '^https://'),
  file_name text,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  version text not null default '1.0',
  checksum_sha256 text check (checksum_sha256 is null or checksum_sha256 ~ '^[0-9a-f]{64}$'),
  is_current boolean not null default true,
  uploaded_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  check (
    (kind = 'external_link' and external_url is not null)
    or (kind <> 'external_link' and storage_path is not null)
  )
);

create index product_files_product_idx on public.product_files (product_id);

create table public.product_changelog (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  version text not null,
  notes jsonb not null default '{}'::jsonb,
  released_at date not null default current_date,
  created_at timestamptz not null default now(),
  unique (product_id, version)
);

create table public.bundle_items (
  bundle_id uuid not null references public.products (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete restrict,
  sort_order integer not null default 0,
  primary key (bundle_id, product_id),
  check (bundle_id <> product_id)
);

create table public.collections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  title jsonb not null,
  description jsonb not null default '{}'::jsonb,
  featured_product_id uuid references public.products (id) on delete set null,
  is_published boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger collections_updated_at before update on public.collections
  for each row execute function public.set_updated_at();

create table public.collection_products (
  collection_id uuid not null references public.collections (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  sort_order integer not null default 0,
  primary key (collection_id, product_id)
);

-- ---------------------------------------------------------------------
-- Coupons (validated on the server only)
-- ---------------------------------------------------------------------

create table public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'),
  type text not null check (type in ('percent', 'fixed')),
  amount numeric(12, 2) not null check (amount > 0),
  currency char(3) check (currency is null or currency ~ '^[A-Z]{3}$'),
  min_order_amount numeric(12, 2) check (min_order_amount is null or min_order_amount >= 0),
  product_ids uuid[] not null default '{}',
  collection_ids uuid[] not null default '{}',
  starts_at timestamptz,
  expires_at timestamptz,
  max_uses integer check (max_uses is null or max_uses > 0),
  per_user_limit integer check (per_user_limit is null or per_user_limit > 0),
  times_used integer not null default 0,
  is_active boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (type <> 'percent' or amount <= 100),
  check (type <> 'fixed' or currency is not null),
  check (expires_at is null or starts_at is null or expires_at > starts_at)
);

create trigger coupons_updated_at before update on public.coupons
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------
-- Orders & payments (server-authoritative)
-- ---------------------------------------------------------------------

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  user_id uuid not null references public.profiles (id) on delete restrict,
  email text not null,
  status text not null default 'pending'
    check (status in ('pending', 'payment_pending', 'paid', 'failed', 'cancelled', 'refunded')),
  currency char(3) not null check (currency ~ '^[A-Z]{3}$'),
  subtotal_amount numeric(12, 2) not null check (subtotal_amount >= 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  coupon_id uuid references public.coupons (id) on delete set null,
  coupon_code text,
  provider text,
  -- Orders created through the development sandbox provider.
  is_test boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz,
  cancelled_at timestamptz,
  refunded_at timestamptz,
  check (total_amount = subtotal_amount - discount_amount)
);

create index orders_user_idx on public.orders (user_id, created_at desc);
create index orders_status_idx on public.orders (status);

create trigger orders_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete restrict,
  title_snapshot jsonb not null,
  unit_amount numeric(12, 2) not null check (unit_amount >= 0),
  discount_amount numeric(12, 2) not null default 0 check (discount_amount >= 0),
  currency char(3) not null,
  license_tier text not null,
  version_at_purchase text not null,
  created_at timestamptz not null default now(),
  unique (order_id, product_id)
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  provider text not null,
  provider_session_id text,
  provider_payment_id text,
  status text not null default 'created'
    check (status in ('created', 'pending', 'succeeded', 'failed', 'cancelled', 'refunded')),
  amount numeric(12, 2) not null,
  currency char(3) not null,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, provider_session_id)
);

create index payments_order_idx on public.payments (order_id);

create trigger payments_updated_at before update on public.payments
  for each row execute function public.set_updated_at();

-- Idempotency log for provider webhooks: each event is processed once.
create table public.payment_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  event_id text not null,
  event_type text not null,
  order_id uuid references public.orders (id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, event_id)
);

-- Access rights. A product is in a user's library while an unrevoked
-- entitlement exists. Created only by fulfil_order().
create table public.entitlements (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete restrict,
  order_id uuid not null references public.orders (id) on delete cascade,
  license_tier text not null,
  granted_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique (user_id, product_id, order_id)
);

create index entitlements_user_idx on public.entitlements (user_id) where revoked_at is null;

create table public.coupon_redemptions (
  id uuid primary key default gen_random_uuid(),
  coupon_id uuid not null references public.coupons (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  order_id uuid not null unique references public.orders (id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Download log (no IP addresses are stored).
create table public.downloads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles (id) on delete set null,
  product_id uuid references public.products (id) on delete set null,
  file_id uuid references public.product_files (id) on delete set null,
  order_id uuid references public.orders (id) on delete set null,
  status text not null check (status in ('success', 'denied', 'error')),
  reason text,
  user_agent text check (user_agent is null or char_length(user_agent) <= 300),
  created_at timestamptz not null default now()
);

create index downloads_user_idx on public.downloads (user_id, created_at desc);

-- ---------------------------------------------------------------------
-- Customer data
-- ---------------------------------------------------------------------

create table public.wishlist_items (
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.cart_items (
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  title text check (title is null or char_length(title) <= 120),
  body text not null check (char_length(body) between 20 and 4000),
  author_name text not null check (char_length(author_name) between 1 and 120),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  -- Set by trigger from real ownership; never trusted from the client.
  verified_purchase boolean not null default false,
  moderated_by uuid references public.profiles (id) on delete set null,
  moderated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, user_id)
);

create index reviews_product_idx on public.reviews (product_id) where status = 'approved';

create trigger reviews_updated_at before update on public.reviews
  for each row execute function public.set_updated_at();

create table public.newsletter_subscribers (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  locale text not null default 'ru' check (locale in ('ru', 'en', 'uz')),
  status text not null default 'subscribed' check (status in ('subscribed', 'unsubscribed')),
  source text,
  created_at timestamptz not null default now(),
  unsubscribed_at timestamptz
);

create unique index newsletter_email_idx on public.newsletter_subscribers (lower(email));

-- ---------------------------------------------------------------------
-- Content, settings, audit, analytics
-- ---------------------------------------------------------------------

create table public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  title jsonb not null,
  excerpt jsonb not null default '{}'::jsonb,
  -- Markdown per locale, rendered as escaped text (no raw HTML).
  body jsonb not null default '{}'::jsonb,
  cover_path text,
  author_name text not null default 'Vektor Lab',
  related_product_ids uuid[] not null default '{}',
  seo_title jsonb,
  seo_description jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger blog_posts_updated_at before update on public.blog_posts
  for each row execute function public.set_updated_at();

create table public.site_settings (
  key text primary key check (key ~ '^[a-z0-9_.]+$'),
  value jsonb not null,
  updated_by uuid references public.profiles (id) on delete set null,
  updated_at timestamptz not null default now()
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles (id) on delete set null,
  actor_email text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text,
  diff jsonb,
  created_at timestamptz not null default now()
);

create index audit_logs_created_idx on public.audit_logs (created_at desc);

create table public.analytics_events (
  id bigint generated always as identity primary key,
  name text not null check (name in (
    'page_view', 'product_view', 'search', 'filter', 'wishlist_add', 'add_to_cart', 'remove_from_cart',
    'begin_checkout', 'payment_start', 'payment_success', 'payment_failed', 'download', 'review_submit')),
  product_id uuid references public.products (id) on delete set null,
  user_id uuid references public.profiles (id) on delete set null,
  session_id text check (session_id is null or char_length(session_id) <= 64),
  path text check (path is null or char_length(path) <= 300),
  props jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index analytics_events_name_idx on public.analytics_events (name, created_at desc);

-- ---------------------------------------------------------------------
-- Ownership, reviews and rating aggregation
-- ---------------------------------------------------------------------

create or replace function public.user_owns_product(p_product_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.entitlements
    where user_id = auth.uid() and product_id = p_product_id and revoked_at is null
  );
$$;

-- Reviews: identity, ownership flag and moderation state are set here,
-- not by the client.
create or replace function public.prepare_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.verified_purchase := exists (
      select 1 from public.entitlements
      where user_id = new.user_id and product_id = new.product_id and revoked_at is null
    );
    if coalesce(auth.role(), '') <> 'service_role' then
      new.status := 'pending';
      new.moderated_by := null;
      new.moderated_at := null;
    end if;
  end if;
  return new;
end;
$$;

create trigger reviews_prepare before insert on public.reviews
  for each row execute function public.prepare_review();

create or replace function public.refresh_product_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target uuid := coalesce(new.product_id, old.product_id);
begin
  update public.products p
  set rating_average = stats.avg_rating,
      rating_count = stats.cnt
  from (
    select round(avg(rating)::numeric, 2) as avg_rating, count(*)::int as cnt
    from public.reviews
    where product_id = target and status = 'approved' and verified_purchase
  ) stats
  where p.id = target;
  return null;
end;
$$;

create trigger reviews_rating after insert or update or delete on public.reviews
  for each row execute function public.refresh_product_rating();

create or replace function public.count_download()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'success' and new.product_id is not null then
    update public.products set download_count = download_count + 1 where id = new.product_id;
  end if;
  return null;
end;
$$;

create trigger downloads_count after insert on public.downloads
  for each row execute function public.count_download();

-- ---------------------------------------------------------------------
-- Order fulfilment (called by the server with the service role)
-- Atomic and idempotent: a second call for a paid order is a no-op.
-- ---------------------------------------------------------------------

create or replace function public.fulfil_order(
  p_order_id uuid,
  p_provider text,
  p_provider_payment_id text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
begin
  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'Order % not found', p_order_id;
  end if;

  if v_order.status = 'paid' then
    return false;
  end if;

  if v_order.status not in ('pending', 'payment_pending', 'failed') then
    raise exception 'Order % cannot be fulfilled from status %', p_order_id, v_order.status;
  end if;

  update public.orders
  set status = 'paid', paid_at = now(), provider = coalesce(p_provider, provider)
  where id = p_order_id;

  update public.payments
  set status = 'succeeded', provider_payment_id = coalesce(p_provider_payment_id, provider_payment_id)
  where order_id = p_order_id and provider = p_provider and status in ('created', 'pending', 'failed');

  insert into public.entitlements (user_id, product_id, order_id, license_tier)
  select v_order.user_id, oi.product_id, v_order.id, oi.license_tier
  from public.order_items oi
  where oi.order_id = v_order.id
  on conflict (user_id, product_id, order_id) do nothing;

  -- Bundles grant access to their included products as well.
  insert into public.entitlements (user_id, product_id, order_id, license_tier)
  select v_order.user_id, bi.product_id, v_order.id, oi.license_tier
  from public.order_items oi
  join public.bundle_items bi on bi.bundle_id = oi.product_id
  where oi.order_id = v_order.id
  on conflict (user_id, product_id, order_id) do nothing;

  if v_order.coupon_id is not null then
    insert into public.coupon_redemptions (coupon_id, user_id, order_id)
    values (v_order.coupon_id, v_order.user_id, v_order.id)
    on conflict (order_id) do nothing;
    update public.coupons set times_used = times_used + 1 where id = v_order.coupon_id;
  end if;

  delete from public.cart_items
  where user_id = v_order.user_id
    and product_id in (select product_id from public.order_items where order_id = v_order.id);

  return true;
end;
$$;

create or replace function public.mark_order_refunded(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.orders set status = 'refunded', refunded_at = now()
  where id = p_order_id and status = 'paid';
  update public.payments set status = 'refunded' where order_id = p_order_id and status = 'succeeded';
  update public.entitlements set revoked_at = now() where order_id = p_order_id and revoked_at is null;
end;
$$;

revoke execute on function public.fulfil_order(uuid, text, text) from public, anon, authenticated;
revoke execute on function public.mark_order_refunded(uuid) from public, anon, authenticated;

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------

alter table public.profiles enable row level security;
alter table public.creators enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_files enable row level security;
alter table public.product_changelog enable row level security;
alter table public.bundle_items enable row level security;
alter table public.collections enable row level security;
alter table public.collection_products enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.entitlements enable row level security;
alter table public.coupon_redemptions enable row level security;
alter table public.downloads enable row level security;
alter table public.wishlist_items enable row level security;
alter table public.cart_items enable row level security;
alter table public.reviews enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.blog_posts enable row level security;
alter table public.site_settings enable row level security;
alter table public.audit_logs enable row level security;
alter table public.analytics_events enable row level security;

-- Profiles: own row; admins read all. Only some columns are user-editable.
create policy profiles_select on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_admin());
create policy profiles_update_own on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
revoke update on public.profiles from anon, authenticated;
grant update (full_name, locale, marketing_opt_in) on public.profiles to authenticated;

-- Creators: public read of active creators; staff manage.
create policy creators_read on public.creators for select
  using (status = 'active' or public.is_staff());
create policy creators_staff on public.creators for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- Catalog: public reads published content; staff manage everything.
create policy categories_read on public.categories for select
  using (is_active or public.is_staff());
create policy categories_staff on public.categories for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy products_read on public.products for select
  using (status = 'published' or public.is_staff());
create policy products_staff on public.products for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy product_images_read on public.product_images for select
  using (exists (select 1 from public.products p where p.id = product_id and (p.status = 'published' or public.is_staff())));
create policy product_images_staff on public.product_images for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy product_files_owner_read on public.product_files for select to authenticated
  using (public.is_staff() or public.user_owns_product(product_id));
create policy product_files_staff on public.product_files for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy product_changelog_read on public.product_changelog for select
  using (exists (select 1 from public.products p where p.id = product_id and (p.status = 'published' or public.is_staff())));
create policy product_changelog_staff on public.product_changelog for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy bundle_items_read on public.bundle_items for select
  using (exists (select 1 from public.products p where p.id = bundle_id and (p.status = 'published' or public.is_staff())));
create policy bundle_items_staff on public.bundle_items for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy collections_read on public.collections for select
  using (is_published or public.is_staff());
create policy collections_staff on public.collections for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy collection_products_read on public.collection_products for select
  using (exists (select 1 from public.collections c where c.id = collection_id and (c.is_published or public.is_staff())));
create policy collection_products_staff on public.collection_products for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

-- Coupons: admins only (validation happens server-side with the service role).
create policy coupons_admin on public.coupons for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Orders & related: customers read their own; only the server writes.
create policy orders_read on public.orders for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
create policy order_items_read on public.order_items for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin())));
create policy payments_read on public.payments for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin())));
create policy payment_events_admin on public.payment_events for select to authenticated
  using (public.is_admin());
create policy entitlements_read on public.entitlements for select to authenticated
  using (user_id = auth.uid() or public.is_admin());
create policy coupon_redemptions_admin on public.coupon_redemptions for select to authenticated
  using (public.is_admin());
create policy downloads_read on public.downloads for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

-- Wishlist & cart: fully owned by the user.
create policy wishlist_own on public.wishlist_items for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy cart_own on public.cart_items for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Reviews: approved reviews are public; owners see their own; only buyers
-- may create one (pending); only admins moderate.
create policy reviews_read on public.reviews for select
  using (status = 'approved' or user_id = auth.uid() or public.is_admin());
create policy reviews_insert_buyer on public.reviews for insert to authenticated
  with check (user_id = auth.uid() and status = 'pending' and public.user_owns_product(product_id));
create policy reviews_moderate on public.reviews for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
create policy reviews_delete on public.reviews for delete to authenticated
  using (user_id = auth.uid() or public.is_admin());

create policy newsletter_admin on public.newsletter_subscribers for select to authenticated
  using (public.is_admin());

create policy blog_read on public.blog_posts for select
  using (status = 'published' or public.is_staff());
create policy blog_staff on public.blog_posts for all to authenticated
  using (public.is_staff()) with check (public.is_staff());

create policy settings_admin on public.site_settings for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy audit_read on public.audit_logs for select to authenticated
  using (public.is_admin());
create policy audit_insert_staff on public.audit_logs for insert to authenticated
  with check (public.is_staff() and actor_id = auth.uid());

create policy analytics_admin on public.analytics_events for select to authenticated
  using (public.is_admin());

-- ---------------------------------------------------------------------
-- Storage
--   product-media  (public): thumbnails, gallery, OG images
--   product-files  (private): paid deliverables — signed URLs only
-- ---------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-media', 'product-media', true, 10485760,
        array['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/gif'])
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('product-files', 'product-files', false)
on conflict (id) do nothing;

create policy "media: public read" on storage.objects for select
  using (bucket_id = 'product-media');
create policy "media: staff insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'product-media' and public.is_staff());
create policy "media: staff update" on storage.objects for update to authenticated
  using (bucket_id = 'product-media' and public.is_staff());
create policy "media: staff delete" on storage.objects for delete to authenticated
  using (bucket_id = 'product-media' and public.is_staff());

create policy "files: staff read" on storage.objects for select to authenticated
  using (bucket_id = 'product-files' and public.is_staff());
create policy "files: staff insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'product-files' and public.is_staff());
create policy "files: staff update" on storage.objects for update to authenticated
  using (bucket_id = 'product-files' and public.is_staff());
create policy "files: staff delete" on storage.objects for delete to authenticated
  using (bucket_id = 'product-files' and public.is_staff());
